### ISSUE TITLE
ValueError "expects a string for argument"

### ISSUE THREAD

**Issue by Lartza** [alfg/murmur-rest#16]
It seems the ascii encoding is mentioned in #5 as possible being incorrect.

It also seems it totally is as the endpoint refuses to start, removing the two encodes in app/\__init__.py and all seems to work.

Ice 3.6.2

```
Traceback (most recent call last):
  File "runserver.py", line 1, in <module>
    from app import app
  File "/home/lartza/murmur-rest/app/__init__.py", line 45, in <module>
    proxy = ice.stringToProxy(test)
  File "/usr/lib/python3.5/site-packages/Ice.py", line 591, in stringToProxy
    return self._impl.stringToProxy(str)
ValueError: stringToProxy expects a string for argument 'str'
!! 05/13/16 11:48:42.937 error: communicator not destroyed during global destruction.
```

```
Traceback (most recent call last):
  File "runserver.py", line 1, in <module>
    from app import app
  File "/home/lartza/murmur-rest/app/__init__.py", line 46, in <module>
    ice.getImplicitContext().put("secret", secret)
  File "/usr/lib/python3.5/site-packages/Ice.py", line 981, in put
    return self._impl.put(key, value)
ValueError: put expects a string for argument 'value'
!! 05/13/16 11:49:39.555 error: communicator not destroyed during global destruction.
```

**Comment by Lartza** [comment]
I am also using Python 3.5.1, it seems murmur-rest is supposed to be run with Python 2 but it's not mentioned anywhere.

**Comment by Lartza** [comment]
Using Python 2 does not have this issue with Ice 3.6.2

**Comment by alfg** [comment]
Hi @Lartza. Thanks for pointing this out. I've never tested this project on Python 3, but I'll be sure to add this into the readme soon!

Thanks!
