### ISSUE TITLE
Help me!

### ISSUE THREAD

**Issue by notedays** [alfg/murmur-rest#25]
Hello. alfg! 
I want to test your api.
And I've done creating new server through this API.
(with Docker) 

The Server created by API's address is 0.0.0.0:64738. 
But I can't connect to the server with other client program of mumble like 'plumble'.
How can I connect to that server? 

plz help me :(

**Comment by alfg** [comment]
Hi @notedays, 

Do you have a docker config you can share? It sounds like maybe you're not exposing the ports via docker. For example, check the docker-compose on guildbit:
https://github.com/alfg/guildbit/blob/master/docker-compose.yml#L19

**Comment by notedays** [comment]
Thank you so much!! I can connect to the server made by API now!!!
But I don't know why the server's port begins from 64738 
even though, I put 50000 into mumble-server.ini. 

This is my port setting in mumble-server.ini 
( the file in repository and in etc/mumble-server.ini is totally same)  
==============================
# Port to bind TCP and UDP sockets to
port=50000
==============================

**Comment by alfg** [comment]
Hi @notedays, 

Do you have any existing virtual servers running? When creating a new server via:
```
POST /servers/
```
It will create the server and increment the port by default. Unless you provide a `port` in the post form data.

**Comment by alfg** [comment]
Sorry for late response!

Try doing a `DELETE /servers/:serverId/`, instead of `DELETE /servers/:serverId`. Notice the trailing slash. 

It seems to give 500 error when not using the trailing slash. I'll look into fixing this.

**Comment by alfg** [comment]
Ok, I think I found the issue. Can you pull the latest and try again?

**Comment by notedays** [comment]
I pulled latest and tried again but, I got this.

```

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/app/api.py", line 430, in channel_del_channel
    oldchannel = server.getRegistration(int(channel))
  File "/opt/Murmur.ice", line 3508, in getRegistration

InvalidUserException: exception ::Murmur::InvalidUserException
{
}
```

**Comment by alfg** [comment]
Updated the Docker repo as well.

**Comment by notedays** [comment]
Sorry for late response.

I didn't want to bother you.

I have trouble adjust latest version after pulling.
So I tried to fix this but it doesn't work well.. :(

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 268, in proxy
    response = view(**request.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_classful.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/opt/app/api.py", line 430, in channel_del_channel
    oldchannel = server.getRegistration(int(channel))
  File "/opt/Murmur.ice", line 3508, in getRegistration

InvalidUserException: exception ::Murmur::InvalidUserException
``` 

After pulling it, even though ```oldchannel = server.getRegistration(int(channel))``` isn't, 
the trace show this ! 

I don't know why ... XD

**Comment by alfg** [comment]
Hey, no worries on asking for help. :)

Are you building the repo via docker locally? or through the `alfg/murmur-rest` repo? You can try:

```
docker build --no-cache -t murmur-rest .
```

**Comment by notedays** [comment]
I build docker with --no-cache option and now it works!!!!!!

Thank you So much!!!!!!!!!  :)   :D   👍  
Have a nice day!

**Comment by alfg** [comment]
Great! Enjoy!

**Comment by notedays** [comment]
Hi @alfg !

Can I ask one more?!

I want to two things to change and I have changed mumble-server.ini 
but it doesn't changed.

1. Fix the password of 'SUPERUSER' 
2. Remove global auto ban for specific IP 

I have changed 'mumble-server.ini' and done 'docker build' too.

How can I do this??
